//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 16-2-2018 07:50:39
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using APITaskManagement.Logic.Common;

namespace APITaskManagement.Logic.Management
{

    /// <summary>
    /// There are no comments for APITaskManagement.Logic.Management.Role, APITaskManagement.Logic in the schema.
    /// </summary>
    public partial class Role : Entity<int>
    {
        /// <summary>
        /// There are no comments for Role constructor in the schema.
        /// </summary>
        public Role()
        {
            ChildRoles = new HashSet<Role>();
            Users = new HashSet<User>();
            
        }


        /// <summary>
        /// There are no comments for ChildRoles in the schema.
        /// </summary>
        public virtual ISet<Role> ChildRoles
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for ParentRole in the schema.
        /// </summary>
        public virtual Role ParentRole
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public virtual ISet<User> Users
        {
            get;
            set;
        }
    }

}
