//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 16-2-2018 07:50:39
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using APITaskManagement.Logic.Common;
using APITaskManagement.Logic.Schedulers;

namespace APITaskManagement.Logic.Management
{

    /// <summary>
    /// There are no comments for APITaskManagement.Logic.Management.Url, APITaskManagement.Logic in the schema.
    /// </summary>
    public partial class Url : Entity<int>
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Url constructor in the schema.
        /// </summary>
        protected Url()
        {
           
            OnCreated();
        }

        public Url(string name,
            string address,
            Interval inactivityTimeout) : this()
        {
            InactivityTimeout = inactivityTimeout;
            Name = name;
            Address = address;
        }

        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public virtual string Address
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for InactivityTimeout in the schema.
        /// </summary>
        public virtual Interval InactivityTimeout
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for ExternalUrl in the schema.
        /// </summary>
        public virtual string ExternalUrl
        {
            get;
            set;
        }

        public virtual AccessType AccessType { get; set; }

        public virtual bool MonitorInactivity { get; set; }

        public virtual bool Reachable { get; set; }

    }

}
