//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 16-2-2018 07:50:39
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using APITaskManagement.Logic.Common;

namespace APITaskManagement.Logic.Schedulers
{

    /// <summary>
    /// There are no comments for APITaskManagement.Logic.Schedulers.Target, APITaskManagement.Logic in the schema.
    /// </summary>
    public partial class Target : Entity<int>
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Target constructor in the schema.
        /// </summary>
        protected Target()
        {
           
            OnCreated();
        }

        public Target(int targetId,
            string crdCode,
            string description) : this()
        {
            TargetId = targetId;
            CrdCode = crdCode;
            Description = description;
        }

        /// <summary>
        /// There are no comments for TargetId in the schema.
        /// </summary>
        public virtual int TargetId
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for CrdCode in the schema.
        /// </summary>
        public virtual string CrdCode
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    }

}
